[package]
name = "rpi-fan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.anyhow]
version = "1.0.57"
features = ["backtrace"]

[dependencies.rppal]
git = "https://github.com/golemparts/rppal.git"
rev = "54e54cbe17293044eaf77bc599631c0ecc572f91"

[profile.release]
strip = true
opt-level = "s"
lto = true