# Builds the web application
FROM rust:1.60.0-slim

COPY . /src

RUN rustup target add wasm32-unknown-unknown

RUN apt-get update
RUN apt-get install wget -y

WORKDIR /src/frontend

RUN wget -qO- https://github.com/thedodd/trunk/releases/download/v0.15.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
RUN ./trunk build --release